Add support for `DonutSwin` models (#320)
* Add `add_special_tokens` option to tokenizers

* Improve error messages for loading processors

* Add `DonutFeatureExtractor`

* Add `DonutSwinModel` and `MBartForCausalLM` models

* Fix `addPastKeyValues` for `VisionEncoderDecoder` models

* Add `Donut` to list of supported models

* Make encode parameters optional

* Support batched decoder input ids

* Remove unused import

* Add `do_thumbnail` for donut image processing

* Fix `TypeError: decoder_input_ids[i].map is not a function`

* Only pad if width and height specified in size

* Only pad if `pad_size` is defined

* Only cut `decoder_input_ids` if past model output

* Add donut model

* Add example usage to JSDoc for `DonutSwinModel`

* Add support for `DocumentQuestionAnsweringPipeline`

* Add simple document question answering unit test

* Add listed support for document QA pipeline